### ISSUE TITLE
New release/Docker

### ISSUE THREAD

**Issue by bhack** [voidmainvoid95/gst-nvmaxine#2]
Do you plan to update it for the new Maxine release `0.7.2`?

I think that you could also simplify the step in your Readme if you can start directly `FROM` a TensorRT official docker image in your `Dockerfile`

**Comment by voidmainvoid95** [comment]
Hi, I've updated maxine videofx to latest version.  Thanks for your suggestion on using official TensorRT image!  
I've tried before to use one of those images, however it was hard to find a version with matches all maxine requirements.  The version that I've used this time have a  newer cudnn version (8.7.0), but all works normally as in custom docker image with cudnn 8.6.0.

**Comment by bhack** [comment]
Thank you, the installation process improved a lot.
